import React, { useState, useEffect } from 'react';
import { Modal } from '../components/Modal';
import { 
  Search, 
  ArrowRight, 
  Bookmark, 
  BookmarkCheck
} from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Guide } from '../types';

interface ExtendedGuide extends Guide {
  format?: 'guide' | 'article' | 'exercise' | 'audio';
  keyTakeaway?: string;
  relatedToolLink?: string;
  relatedToolLabel?: string;
}

const EXTENDED_INITIAL_GUIDES: ExtendedGuide[] = [
  {
    id: 'why-stress-paralyzes',
    title: 'Why does stress make it difficult to start?',
    category: 'Stress & Anxiety',
    format: 'article',
    readTime: '4 min read',
    summary: 'The neuroscience of task paralysis, executive overwhelm, and how to gently break the freeze response.',
    keyTakeaway: 'Task avoidance is not laziness—it is your amygdala perceiving ambiguous work as a threat.',
    relatedToolLink: '/grounding',
    relatedToolLabel: 'Try Box Breathing Pacer',
    content: `When you sit down to start an assignment or study, your brain evaluates the effort, emotional stakes, and fear of failure. If the perceived difficulty is too high, your nervous system triggers a subtle "freeze" state.

### 1. Lower the Activation Energy
Instead of aiming to finish a 5-page essay, set a goal to write **one terrible sentence**. Removing the perfection requirement immediately reduces amygdala alarm.

### 2. The 5-Minute Rule
Commit to working on the task for exactly 5 minutes with a visible timer. Tell yourself you have full permission to stop once the timer rings. 80% of the time, overcoming the initial friction keeps you going.

### 3. Clear Visual Distractions
Visual clutter in your peripheral vision consumes subconscious mental RAM. Clear only the 12 inches directly around your keyboard.`,
    status: 'published'
  },
  {
    id: 'anxiety-grounding',
    title: 'Somatic grounding for racing thoughts',
    category: 'Stress & Anxiety',
    format: 'exercise',
    readTime: '3 min exercise',
    summary: 'Simple physiological techniques to pull autonomic awareness away from panic into the physical room.',
    keyTakeaway: 'The body leads the mind. Slow your exhalations to physically force heart rate deceleration.',
    relatedToolLink: '/grounding',
    relatedToolLabel: 'Open 5-4-3-2-1 Sensory Tool',
    content: `Anxiety triggers the sympathetic nervous system. You cannot out-think panic with more thinking—you must use somatic sensory anchors.

### 1. The Physiological Sigh
Take two quick sniffs in through your nose (one deep, one sharp top-off), followed by a slow, unforced exhalation through your mouth for 6 seconds. Repeat 3 times to reopen collapsed lung alveoli.

### 2. Temperature Reset
Hold a cool glass of water or place a damp cloth on the back of your neck. The sudden temperature shift engages the mammalian dive reflex.`,
    status: 'published'
  },
  {
    id: 'cbt-thought-traps',
    title: 'Recognizing the 6 core cognitive distortions',
    category: 'Cognitive Reframing',
    format: 'guide',
    readTime: '6 min read',
    summary: 'A clinical primer on Catastrophizing, All-or-Nothing thinking, and Socratic evidence testing.',
    keyTakeaway: 'Thoughts are automatic hypotheses generated by a tired brain, not objective reality.',
    relatedToolLink: '/untangle',
    relatedToolLabel: 'Open CBT Thought Reframer',
    content: `Cognitive distortions are internal mental filters that distort our perception of events:

1. **Catastrophizing:** Assuming the worst imaginable outcome is inevitable.
2. **Mind Reading:** Convinced others are judging you with zero verbal confirmation.
3. **All-or-Nothing Thinking:** Viewing any performance below 100% as an absolute failure.
4. **Emotional Reasoning:** "Because I feel anxious, the situation must be dangerous."

### Testing the Evidence
Whenever a painful thought appears, write it down and ask:
* What is 1 piece of hard, factual evidence that disproves this thought?
* What would I say to a friend who had this exact thought?`,
    status: 'published'
  },
  {
    id: 'sleep-hygiene-architecture',
    title: 'The 4-stage architecture of restful sleep',
    category: 'Sleep & Rest',
    format: 'article',
    readTime: '5 min read',
    summary: 'How circadian rhythm alignment and blue-light winddowns restore cognitive memory consolidation.',
    keyTakeaway: 'Consistency in wake time matters more than consistency in bedtime.',
    relatedToolLink: '/soundscape',
    relatedToolLabel: 'Play 432Hz Ambient Soundscape',
    content: `Sleep is when your brain cleanses metabolic waste and organizes learned memories.

### 1. The Anchor Wake Time
Keep your morning wake time within a 30-minute window every day, including weekends. This sets your melatonin timer for the coming night.

### 2. Acoustic Buffer
Block sudden ambient nighttime disturbances using low-frequency brown noise or soft rain audio.`,
    status: 'published'
  },
  {
    id: 'binaural-audio-primer',
    title: 'How 432Hz and Alpha frequencies calm sensory overload',
    category: 'Sleep & Rest',
    format: 'audio',
    readTime: '10 min audio session',
    summary: 'Understanding binaural beats, acoustic resonance, and brainwave entrainment for focused study.',
    keyTakeaway: 'Binaural beats gently synchronize cerebral hemispheres into low-frequency alpha focus.',
    relatedToolLink: '/soundscape',
    relatedToolLabel: 'Open Sound Sanctuary',
    content: `When two tones with slightly different frequencies are played into each ear, the brain perceives a rhythmic beat equal to the mathematical difference.

* **Alpha Waves (8–12 Hz):** Calm alertness, reflective daydreaming, and reduced anxiety.
* **432 Hz Tuning:** A harmonic frequency traditionally favored for acoustic relaxation and meditation.`,
    status: 'published'
  }
];

export const Resources: React.FC = () => {
  const [guides] = useState<ExtendedGuide[]>(EXTENDED_INITIAL_GUIDES);
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [activeFormat, setActiveFormat] = useState<'all' | 'guide' | 'article' | 'exercise' | 'audio'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedGuide, setSelectedGuide] = useState<ExtendedGuide | null>(null);

  // Bookmarks & Recently Viewed
  const [savedIds, setSavedIds] = useState<string[]>(() => {
    try {
      const stored = localStorage.getItem('haven_saved_resources');
      return stored ? JSON.parse(stored) : ['why-stress-paralyzes'];
    } catch {
      return ['why-stress-paralyzes'];
    }
  });

  const [recentlyViewedIds, setRecentlyViewedIds] = useState<string[]>(() => {
    try {
      const stored = localStorage.getItem('haven_recent_resources');
      return stored ? JSON.parse(stored) : ['why-stress-paralyzes', 'anxiety-grounding'];
    } catch {
      return ['why-stress-paralyzes', 'anxiety-grounding'];
    }
  });

  useEffect(() => {
    localStorage.setItem('haven_saved_resources', JSON.stringify(savedIds));
  }, [savedIds]);

  useEffect(() => {
    localStorage.setItem('haven_recent_resources', JSON.stringify(recentlyViewedIds));
  }, [recentlyViewedIds]);

  const toggleBookmark = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (savedIds.includes(id)) {
      setSavedIds(savedIds.filter(i => i !== id));
    } else {
      setSavedIds([...savedIds, id]);
    }
  };

  const handleOpenGuide = (guide: ExtendedGuide) => {
    setSelectedGuide(guide);
    const updated = [guide.id, ...recentlyViewedIds.filter(i => i !== guide.id)].slice(0, 4);
    setRecentlyViewedIds(updated);
  };

  const categories = ['All', 'Stress & Anxiety', 'Cognitive Reframing', 'Sleep & Rest', 'School & Focus'];

  const filteredGuides = guides.filter((g) => {
    const matchesCategory = activeCategory === 'All' || g.category === activeCategory;
    const matchesFormat = activeFormat === 'all' || g.format === activeFormat;
    const q = searchQuery.toLowerCase();
    const matchesSearch = g.title.toLowerCase().includes(q) || 
                          g.summary.toLowerCase().includes(q) ||
                          (g.keyTakeaway && g.keyTakeaway.toLowerCase().includes(q));
    return matchesCategory && matchesFormat && matchesSearch;
  });

  const recentlyViewedGuides = guides.filter(g => recentlyViewedIds.includes(g.id));

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 md:py-20 space-y-16 selection:bg-brand-primary/10">
      
      {/* ── 1. QUIET EDITORIAL MASTHEAD ── */}
      <header className="flex items-baseline justify-between border-b border-border-primary/60 pb-4 text-xs font-semibold text-text-muted tracking-tight">
        <span className="text-[11px] font-black uppercase tracking-widest text-text-secondary">
          RESOURCES & GUIDES
        </span>
        <span className="font-mono text-[11px]">
          Evidence-Based • Curated for Students
        </span>
      </header>

      {/* ── 2. EDITORIAL HERO & SEARCH ── */}
      <section className="space-y-4 max-w-2xl">
        <h1 className="text-3xl md:text-4xl font-extrabold text-text-primary tracking-tight leading-tight">
          Understanding stress,<br />nervous system regulation & sleep.
        </h1>
        <p className="text-xs md:text-sm text-text-secondary font-medium leading-relaxed">
          Short, practical guides and physiological tools written without clinical jargon.
        </p>

        {/* Search Bar */}
        <div className="pt-2">
          <div className="relative">
            <Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted pointer-events-none" />
            <input
              type="text"
              placeholder="Search guides by keyword, e.g. 'paralysis', 'breathing', 'CBT', 'sleep'..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-11 pr-4 py-3 bg-surface-sec border border-border-primary rounded-2xl text-xs md:text-sm font-semibold text-text-primary placeholder:text-text-muted focus:outline-none focus:border-brand-primary transition-colors"
            />
          </div>
        </div>
      </section>

      {/* ── 3. RECENTLY VIEWED ROW (IF APPLICABLE) ── */}
      {searchQuery.trim() === '' && recentlyViewedGuides.length > 0 && (
        <section className="space-y-3 pt-2">
          <div className="flex items-center justify-between text-[11px] font-black uppercase tracking-widest text-text-muted">
            <span>Recently Viewed</span>
            <span>Resume</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {recentlyViewedGuides.slice(0, 2).map((guide) => (
              <div
                key={`recent_${guide.id}`}
                onClick={() => handleOpenGuide(guide)}
                className="p-4 rounded-2xl bg-surface-main border border-border-primary hover:border-brand-primary/40 transition-all cursor-pointer shadow-2xs space-y-1.5 flex flex-col justify-between"
              >
                <div className="space-y-1">
                  <span className="text-[10px] font-mono font-bold text-brand-primary uppercase tracking-wider">
                    {guide.category} • {guide.readTime}
                  </span>
                  <h4 className="text-xs font-bold text-text-primary line-clamp-1">
                    {guide.title}
                  </h4>
                </div>
                <span className="text-[10.5px] font-semibold text-text-muted hover:text-brand-primary inline-flex items-center space-x-1 pt-1">
                  <span>Continue reading</span>
                  <ArrowRight size={11} />
                </span>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* ── 4. CATEGORY & FORMAT SELECTORS ── */}
      <section className="space-y-4">
        {/* Category Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none text-xs font-bold">
          {categories.map((cat) => (
            <button
              key={cat}
              type="button"
              onClick={() => setActiveCategory(cat)}
              className={`px-3.5 py-1.5 rounded-xl border transition-all cursor-pointer shrink-0 ${
                activeCategory === cat
                  ? 'bg-brand-primary text-white border-brand-primary shadow-2xs'
                  : 'bg-surface-main border-border-primary text-text-secondary hover:bg-surface-sec'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Format Sub-Filters */}
        <div className="flex items-center space-x-2 text-[10.5px] font-bold text-text-muted border-b border-border-primary/60 pb-3">
          <span className="uppercase tracking-wider">Format:</span>
          {[
            { id: 'all', label: 'All Formats' },
            { id: 'article', label: 'Articles' },
            { id: 'exercise', label: 'Short Exercises' },
            { id: 'guide', label: 'CBT Guides' },
            { id: 'audio', label: 'Audio' },
          ].map((f) => (
            <button
              key={f.id}
              type="button"
              onClick={() => setActiveFormat(f.id as any)}
              className={`px-2 py-0.5 rounded-lg transition-colors cursor-pointer ${
                activeFormat === f.id ? 'bg-surface-sec text-brand-primary font-black' : 'hover:text-text-primary'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
      </section>

      {/* ── 5. EDITORIAL ARTICLE LIST ── */}
      <section className="space-y-0 divide-y divide-border-primary/70 border-y border-border-primary/70">
        {filteredGuides.length === 0 ? (
          <div className="text-center py-16 space-y-2">
            <h4 className="text-sm font-bold text-text-primary">No resources match your search</h4>
            <p className="text-xs text-text-secondary">
              Try searching for different terms or clearing your category filters.
            </p>
          </div>
        ) : (
          filteredGuides.map((guide) => {
            const isSaved = savedIds.includes(guide.id);
            return (
              <div
                key={guide.id}
                onClick={() => handleOpenGuide(guide)}
                className="py-6 px-2 group flex flex-col md:flex-row md:items-baseline justify-between gap-4 cursor-pointer hover:bg-surface-sec/30 transition-all"
              >
                <div className="space-y-2 max-w-xl">
                  <div className="flex items-center space-x-3 text-[10.5px] font-mono text-text-muted">
                    <span className="font-bold text-brand-primary uppercase tracking-wider">{guide.category}</span>
                    <span>•</span>
                    <span>{guide.readTime}</span>
                  </div>

                  <h3 className="text-base font-extrabold text-text-primary group-hover:text-brand-primary transition-colors">
                    {guide.title}
                  </h3>

                  <p className="text-xs text-text-secondary leading-relaxed font-medium">
                    {guide.summary}
                  </p>
                </div>

                <div className="flex items-center space-x-3 shrink-0 self-end md:self-center">
                  <button
                    type="button"
                    onClick={(e) => toggleBookmark(guide.id, e)}
                    className="p-2 rounded-xl text-text-muted hover:text-brand-primary transition-colors cursor-pointer"
                    title={isSaved ? 'Remove from saved' : 'Save for later'}
                  >
                    {isSaved ? <BookmarkCheck size={16} className="text-brand-primary fill-current" /> : <Bookmark size={16} />}
                  </button>

                  <div className="text-text-muted group-hover:text-brand-primary group-hover:translate-x-1 transition-all">
                    <ArrowRight size={16} />
                  </div>
                </div>
              </div>
            );
          })
        )}
      </section>

      {/* ── FULL ARTICLE READER MODAL ── */}
      <Modal
        isOpen={selectedGuide !== null}
        onClose={() => setSelectedGuide(null)}
        title={selectedGuide?.category || 'Resource'}
      >
        {selectedGuide && (
          <div className="space-y-6 py-2">
            <div className="space-y-2 border-b border-border-primary pb-4">
              <span className="text-[10px] font-mono font-bold text-brand-primary uppercase tracking-wider">
                {selectedGuide.category} • {selectedGuide.readTime}
              </span>
              <h2 className="text-xl font-black text-text-primary tracking-tight">
                {selectedGuide.title}
              </h2>
            </div>

            {selectedGuide.keyTakeaway && (
              <div className="p-4 bg-brand-light/30 border border-brand-primary/20 rounded-2xl space-y-1">
                <span className="text-[9.5px] font-mono font-extrabold uppercase tracking-wider text-brand-primary block">
                  Key Takeaway
                </span>
                <p className="text-xs text-text-primary font-semibold leading-relaxed">
                  "{selectedGuide.keyTakeaway}"
                </p>
              </div>
            )}

            {/* Markdown-style Content Body */}
            <div className="text-xs text-text-secondary leading-relaxed font-medium space-y-4 whitespace-pre-line">
              {selectedGuide.content}
            </div>

            {/* Related Interactive Tool Link */}
            {selectedGuide.relatedToolLink && (
              <div className="pt-4 border-t border-border-primary flex items-center justify-between">
                <span className="text-[11px] text-text-muted font-semibold">Recommended practice:</span>
                <Link
                  to={selectedGuide.relatedToolLink}
                  className="px-4 py-2 bg-brand-primary hover:bg-brand-hover text-white rounded-xl text-xs font-bold transition-all shadow-xs inline-flex items-center space-x-1.5"
                >
                  <span>{selectedGuide.relatedToolLabel || 'Open Tool'}</span>
                  <ArrowRight size={13} />
                </Link>
              </div>
            )}
          </div>
        )}
      </Modal>

    </div>
  );
};
